export const LOAD_COLUMNS = [
	{ title: 'Línea' },
	{ title: 'Contrato' },
	{ title: 'RUC' },
	{ title: 'Razón Social' },
	{ title: 'Fecha' },
	{ title: 'Chasis' },
	{ title: 'Factura' },
	{ title: 'Moneda' },
	{ title: 'Importe' },
	{ title: 'Dealer' },
	{ title: 'Contacto' },
	{ title: 'Celular' },
	{ title: 'Categoría' },
	{ title: 'Área de Negocio' },
	{ title: 'Tipo Bono' },
	{ title: 'Referencia' },
];
