export const LOAD_COLUMNS = [
	{ title: 'Línea' },
	{ title: 'Contrato' },
	{ title: 'RUC' },
	{ title: 'Razón Social' },
	{ title: 'Fecha' },
	{ title: 'Chasis' },
	{ title: 'Factura' },
	{ title: 'Moneda' },
	{ title: 'Importe' },
	{ title: 'Saldo' },
	{ title: 'Tipo' },
	{ title: 'Área de Negocio' },
	{ title: 'Tipo Tarjeta' },
	{ title: 'Referencia' },
];
